"""added_inital_amount_backtest_table

Revision ID: 0b6a30711efd
Revises: 91cff9bd60c0
Create Date: 2025-07-30 17:11:36.753350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6a30711efd'
down_revision: Union[str, Sequence[str], None] = '91cff9bd60c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
