"""added_final_amount_backtest_table

Revision ID: 5126a49438f0
Revises: df2aaa7ec8f3
Create Date: 2025-07-30 18:35:19.638537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5126a49438f0'
down_revision: Union[str, Sequence[str], None] = 'df2aaa7ec8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('final_value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_runs', 'final_value')
    # ### end Alembic commands ###
