"""updated_backtest_table

Revision ID: 91cff9bd60c0
Revises: b6f1857fc136
Create Date: 2025-07-30 11:41:06.456760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91cff9bd60c0'
down_revision: Union[str, Sequence[str], None] = 'b6f1857fc136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'backtest_runs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(None, 'backtest_runs', type_='foreignkey')
    op.drop_column('backtest_runs', 'user_id')
    # ### end Alembic commands ###
