"""added_inital_amount_backtest_table

Revision ID: df2aaa7ec8f3
Revises: 0b6a30711efd
Create Date: 2025-07-30 17:23:36.249797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2aaa7ec8f3'
down_revision: Union[str, Sequence[str], None] = '0b6a30711efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('initial_cash', sa.Integer(), nullable=False))
    op.add_column('backtest_runs', sa.Column('commission', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_runs', 'commission')
    op.drop_column('backtest_runs', 'initial_cash')
    # ### end Alembic commands ###
